### ISSUE TITLE
Lucky number test in GameServiceImplTest

### ISSUE THREAD

**Issue by cboschmans-code** [Book-Microservices-v2/chapter06#1]
Hi,
I am confused.
Why is it given that the badgeprocessor returns a LUCKY_NUMBER badge type while there is no Lucky factor 42 in the attempt.
BR

**Comment by mechero** [comment]
Hi!

The logic in `LuckyNumberBadgeProcessor` (see [this link](https://github.com/Book-Microservices-v2/chapter06/blob/83c12d4b9ed560742f12a9fd9a54f6cbf56b48d8/gamification/src/main/java/microservices/book/gamification/game/badgeprocessors/LuckyNumberBadgeProcessor.java#L20)) returns an empty optional if none of the factors is 42.

Did you find any case where you get the badge for a multiplication without that factor?

**Comment by mechero** [comment]
Now that I'm reading the title of this issue... In case you're referring to the test cases, the first one uses an attempt with the lucky number, check the code [here](https://github.com/Book-Microservices-v2/chapter06/blob/83c12d4b9ed560742f12a9fd9a54f6cbf56b48d8/gamification/src/test/java/microservices/book/gamification/game/badgeprocessors/LuckyNumberBadgeProcessorTest.java#L28).

**Comment by cboschmans-code** [comment]
Yes i' m referring to the  [GameServiceImplTest](https://github.com/Book-Microservices-v2/chapter06/blob/master/gamification/src/test/java/microservices/book/gamification/game/GameServiceImplTest.java) where there is  a LUCKY_NUMBER badgetype given to an attempt without lucky factor 42 , Or at least it looks like it is. The test runs without errors.

**Comment by mechero** [comment]
Ah indeed, good 👁️

You're right, it's confusing. It works because the `BadgeProcessor` interface is mocked, and there is an instruction to make it return a badge for the attempt (see [this line](https://github.com/Book-Microservices-v2/chapter06/blob/83c12d4b9ed560742f12a9fd9a54f6cbf56b48d8/gamification/src/test/java/microservices/book/gamification/game/GameServiceImplTest.java#L54)). It's not using the real implementation.

An attempt with two `1` factors and an inline comment, or an attempt with a `42` would have been clearer. 

Thanks for contributing!

**Comment by cboschmans-code** [comment]
Thanks for the great book !
